---
title: "Assignment 4"
author: "Daniel Fang, Cloris Li"
format: 
  html:
    self-contained: true
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidycensus)
library(tidyverse)
library(tigris)
library(ggplot2)
library(sf)
library(here)
```

# Graph 1

```{r}
ar_income <- get_acs(
  geography = "tract", 
  variables = "B19013_001", 
  state = "VA", 
  county = "Arlington", 
  geometry = TRUE,
  year = 2021,
  progress = FALSE
)

ggplot()+
  geom_sf(data = ar_income, aes(fill = estimate) ) +
  scale_fill_gradient(low = "#cfe8f3" , high = "#062635",
                      labels = scales::dollar,
                      name = "Median Household Income") +
  labs(title = "Median Household Incomes Across Arlington, VA in 2021",
       subtitle = "Highest income households are concentrated in the north",
       caption = "Sources: American Community Survey (ACS) | Tidycensus R package") + 
  theme_minimal() +
  theme(text = element_text(family = "serif"))
```

Graph 1 is a choropleth of the median household income estimates for Arlington, VA and shows the spatial distribution of median household incomes across the region. Each census tract is shaded based on its median household income, with darker shades representing higher incomes and lighter shades lower incomes.

# Graph 2

```{r}
metros <-  get_acs(
  geography = "cbsa",
  variables = "DP03_0021P",
  summary_var = "B01003_001",
  survey = "acs1",
  year = 2019
) %>%
  slice_max(summary_est, n = 20)
```

```{r}
metros %>%
  mutate(NAME = str_remove(NAME, "-.*$")) %>%
  mutate(NAME = str_remove(NAME, ",.*$")) %>%
  ggplot(aes(y = reorder(NAME, estimate), x = estimate)) + 
  geom_col()
```

#Graph 3

```{r}
housing_val <- get_acs(
  geography = "tract",
# median home value
  variables = "B25077_001",
  state = "VA",
# only these counties
  county = c(
    "Arlington",
    "Alexandria",
    "Manassas city",
    "Falls Church"
  )
)%>%
# separate NAME column into columns for tract, county, and state
  separate(
  NAME,
  into = c("tract", "county", "state"),
  sep = ", "
)

```

```{r}
ggplot()+
  geom_density(data = housing_val, aes(x = estimate, fill = county), alpha = 0.4) +
  theme_minimal()
```
